package com.G_1.Recess.MathCompMagtSyst.Challenge;

import com.G_1.Recess.MathCompMagtSyst.Question.Question;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.util.List;

@Entity
@Table(name = "challenges")
@Data
public class Challenge {

@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name = "challenge_id")
private Long challengeId;

@Column(name = "opening_date")
private LocalDate openingDate;

@Column(name = "closing_date")
private LocalDate closingDate;

private Long duration;

@Column(name = "number_of_questions")
private int numberOfQuestions;

@Column(name = "accpart_id")
private Long accpartId;

@OneToMany(mappedBy = "challenge", fetch = FetchType.LAZY)
private List<Question> questions;

// Getters and setters are automatically generated by Lombok @Data

}
